In [1]:
import pandas as pd
import numpy as np
from factor_analyzer import calculate_bartlett_sphericity, calculate_kmo

In [2]:
data = pd.read_pickle('norm_data.pkl')
data.head()

,Cреднеспис.числ.работн,k1,k2,k3,k4,k4_new,k5,k6,k7,k8,...,k12,k13,k14,k15,k16,k17,k18,k19,k20,Year
0,6095.0,0.403809,0.503518,0.548820,0.328302,NaN,0.330954,0.475458,0.833823,0.675877,...,0.451272,0.309298,0.359411,0.340312,0.459953,1.000000,0.554562,0.497247,0.479035,5.0
1,255.0,0.591695,0.653597,0.632007,0.763404,NaN,0.169329,0.543158,0.421875,0.877837,...,0.471764,0.330484,0.592674,0.566433,0.490934,1.000000,0.678800,0.510526,0.458055,5.0
2,114.0,0.300968,0.462057,0.341906,0.000000,NaN,0.379270,0.893999,1.000000,0.645891,...,0.502503,0.083725,0.220906,0.402367,1.000000,0.558105,0.000000,0.371303,0.399927,5.0
3,365.0,1.000000,1.000000,1.000000,0.902599,NaN,0.126387,0.311175,0.433346,0.890587,...,0.564472,1.000000,1.000000,0.942774,0.418881,0.546973,0.854628,1.000000,1.000000,5.0
4,168.0,0.555295,0.464936,0.620328,0.709942,NaN,0.235475,1.000000,0.927524,0.808497,...,0.407338,0.231825,0.403838,0.317202,0.420597,0.496557,0.516877,0.414231,0.426759,5.0

In [3]:
data_k8_drop = data.drop("k8", axis = 1)
data_k8_drop.head()

,Cреднеспис.числ.работн,k1,k2,k3,k4,k4_new,k5,k6,k7,k9,...,k12,k13,k14,k15,k16,k17,k18,k19,k20,Year
0,6095.0,0.403809,0.503518,0.548820,0.328302,NaN,0.330954,0.475458,0.833823,0.529053,...,0.451272,0.309298,0.359411,0.340312,0.459953,1.000000,0.554562,0.497247,0.479035,5.0
1,255.0,0.591695,0.653597,0.632007,0.763404,NaN,0.169329,0.543158,0.421875,0.903975,...,0.471764,0.330484,0.592674,0.566433,0.490934,1.000000,0.678800,0.510526,0.458055,5.0
2,114.0,0.300968,0.462057,0.341906,0.000000,NaN,0.379270,0.893999,1.000000,0.511229,...,0.502503,0.083725,0.220906,0.402367,1.000000,0.558105,0.000000,0.371303,0.399927,5.0
3,365.0,1.000000,1.000000,1.000000,0.902599,NaN,0.126387,0.311175,0.433346,0.999822,...,0.564472,1.000000,1.000000,0.942774,0.418881,0.546973,0.854628,1.000000,1.000000,5.0
4,168.0,0.555295,0.464936,0.620328,0.709942,NaN,0.235475,1.000000,0.927524,0.752390,...,0.407338,0.231825,0.403838,0.317202,0.420597,0.496557,0.516877,0.414231,0.426759,5.0

In [5]:
def data_filter(data):
    return data[[col for col in data.columns if col.startswith("k") and col[1].isdigit()]]

In [6]:
data_full = data_filter(data)
data_mod = data_filter(data_k8_drop)